### ISSUE TITLE
Crashes in cache clear method

### ISSUE THREAD

**Issue by Eilhart** [AliceCA/Overchan-Android#13]
Встречаю такой баг уже второй раз. Приложение падает в галерее, чаще в свернутом состоянии.

Лог прилагаю:
[npelog.txt](https://github.com/AliceCA/Overchan-Android/files/999385/npelog.txt)

**Comment by AliceCA** [comment]
Исправлено https://github.com/AliceCA/Overchan-Android/commit/5f29d43521edde8695a89bf8aa627fd1a590e009
