### ISSUE TITLE
diochan support

### ISSUE THREAD

**Issue by decripter37** [AliceCA/Overchan-Android#15]
Can you make diochan support?

**Comment by AliceCA** [comment]
On which engine does it work? Does it have an api?

**Comment by Eilhart** [comment]
It uses almost-vanilla kusaba engine.

**Comment by AliceCA** [comment]
Read-only version is now implemented. https://github.com/AliceCA/Overchan-Android/commit/c6e63b64281160bf0012c4f68f8311fa6287b5e8
Can someone help with implementation of methods for posting?
