### ISSUE TITLE
Fix brchan

### ISSUE THREAD

**Issue by dimqua** [AliceCA/Overchan-Android#20]
Brchan is now known as [LOLIFOX](https://lolifox.org/).

**Comment by Eilhart** [comment]
It seems brchan.org and lolifox.org use same engine and have almost identical content but different administration.

**Comment by Philolaus** [comment]
Please, add a new module fro lolifox! Also, brchan is pretty much dead.

**Comment by AliceCA** [comment]
https://github.com/AliceCA/Overchan-Android/commit/a60ecef733b57502359e4275a822751ae51d1a25
