### ISSUE TITLE
Captcha auto update

### ISSUE THREAD

**Issue by Vintodrimmer** [AliceCA/Overchan-Android#21]
Good day,

Can you make a toggle for initial captcha loading?
If I have enabled auto-update, it changes the moment I try to enter it. This means that I will never be able to enter the first captcha loaded.

This is very confusing, because you see the numbers, think about entering them and they change.
If, instead, it only loads when I try to enter it for the first time, experience would be more pleasant.

**Comment by AliceCA** [comment]
Now app will refresh captcha only if captcha field is empty. https://github.com/AliceCA/Overchan-Android/commit/b1530b36e4131f59d31e9738452e08e5feecd4f5

**Comment by Vintodrimmer** [comment]
Thanks!
