### ISSUE TITLE
Не открываются некоторые доски на 2ch.hk

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [AliceCA/Overchan-Android#26]
Не получается зайти на некотопые доски с NSFW-контентом, например, /h/. Похоже, что для доступа требуется cookie, подтверждающее отравку поста на любой другой доске, но в Overchan это cookie не сохраняется. Версия 1.0.1 с F-Droid. Другие пользователи сообщают, что в предыдущей версии этой проблемы не было.

**Comment by AliceCA** [comment]
fixed https://github.com/AliceCA/Overchan-Android/commit/79443fd7ca12e008aba8207b011ebe10ed1e2dc4

**Comment by Eilhart** [comment]
> fixed 79443fd

В этом случае куки сохраняются, но свойство 'path' принимает значение '/makaba' – игнорируется значение в заголовке ответа сервера и определяется на основе URL запроса. Как следствие, куки не отсылается при переходе по адресу доски (/h). При этом, если перезапустить приложение, то доступ будет открыт, так как 'path' будет равно '/'.

[Возможная причина](https://issues.apache.org/jira/browse/HTTPCLIENT-1640?focusedCommentId=14507421)

**Comment by ghost** [comment]
удали
