### ISSUE TITLE
Капча. Опять.

### ISSUE THREAD

**Issue by Simaik5** [AliceCA/Overchan-Android#48]
Мылачевская отключена. Постить нельзя. Pizdarique

**Comment by Eilhart** [comment]
Обнови до версии [1.6.0](https://github.com/AliceCA/Overchan-Android/releases/tag/v1.6.0_unofficial), в которой есть гуглокапча и двачекапча.

**Comment by Simaik5** [comment]
Увидел, спасибо огромное за то что этим клиентом до сих пор кто-то еще занимается.
