### ISSUE TITLE
Can't to post on 2ch.hk

### ISSUE THREAD

**Issue by homeless-computing** [AliceCA/Overchan-Android#63]
App version 1.0.2 from f-droid, this is most recent version here. OS is android 4.2.2. Then I'm sending message, I have to get google recaptcha verification (marking pictures and copypasting code). After clicking "submit" button, I'm getting "капча невалидна" error. Was tested without success on /b, /s and /ra boards.

Please, feel free to ask any info about issue, and i'll give any logs or any details required for problem solving.

**Comment by AliceCA** [comment]
Use reCAPTCHA instead.
