### ISSUE TITLE
Вылетает двачь

### ISSUE THREAD

**Issue by hekka228** [AliceCA/Overchan-Android#8]
Клиент выключается, когда захожу на 2ch.hk. С другими бордами все в порядке(к примеру 8чан и 4чан)

**Comment by AliceCA** [comment]
Напишите какую версию android вы используете, а так же модель и производителя устройства. Если есть возможность, то предоставьте логи приложения с ошибкой (logcat). Так же убедитесь, что это не следствие интернет-блокировки сайта.

**Comment by hekka228** [comment]
[Log_2017-04-01_14-33-58.txt](https://github.com/AliceCA/Overchan-Android/files/887574/Log_2017-04-01_14-33-58.txt)

Телефон Samsung Galaxy R I9103, версия 4.0.4, но модифицированная([BACKUP][4.0.4][RePack] XWLP8 India + XWLP2 Poland Deodexed), отсюда https://4pda.ru/forum/index.php?showtopic=369911&st=4380#entry20735522

**Comment by AliceCA** [comment]
Не удалось выяснить, почему происходит ошибка так, как в логах нет сообщений об исключениях, выброшенных из Оверчана, только предупреждения об отсутствии методов.
