### ISSUE TITLE
Attachments duplication

### ISSUE THREAD

**Issue by Eilhart** [AliceCA/Overchan-Android#9]
Already attached files attaches again when resuming to the [posting form](https://github.com/AliceCA/Overchan-Android/blob/0d3a92e55a87af949283188fedb53b2ffc735493/src/nya/miku/wishmaster/ui/posting/PostFormActivity.java).
Same files are added in `onCreate` and then in `onResume` methods.

**Comment by AliceCA** [comment]
Fixed https://github.com/AliceCA/Overchan-Android/commit/89f20ccee28760238c01bcca2a04284d0a9507fc
